export type RootStackParamList = {
    Login: undefined;
    Home: undefined;
    SixMonth: undefined;
    SixWeek: undefined;
    Contact: undefined;
    AboutUs: undefined;
    OurServices: undefined;
    Vision: undefined;
    Phone: undefined;
    phoneNumber: undefined;
    Sewing: undefined;
    Cooking: undefined;
    FirstAid: undefined;
    GardenMaintenance: undefined;
    LifeSkills: undefined;
    Landscaping: undefined;
    ChildMinding: undefined;
    Registration: undefined;
};
